LIBDIR = $(ROOTDIR)/lib/libusb-0.1.12
CFLAGS += -I$(LIBDIR) 
#LDLIBS += -lusb
LDLIBS =
EXEC = usb_modeswitch
SRCS = usb_modeswitch.c

$(EXEC): $(SRCS)
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ $^ $(LDLIBS)

romfs:
	$(ROMFSINST) /bin/$(EXEC)
	$(ROMFSINST) usb_modeswitch.conf /etc/

clean:
	-rm -f $(EXEC) *.o

