# $Id: //WIFI_SOC/release/SDK_4_1_0_0/source/linux-2.6.21.x/arch/xtensa/platform-iss/Makefile#1 $
#
# Makefile for the Xtensa Instruction Set Simulator (ISS)
# "prom monitor" library routines under Linux.
#
# Note! Dependencies are done automagically by 'make dep', which also
# removes any old dependencies. DON'T put your own dependencies here
# unless it's something special (ie not a .c file).
#
# Note 2! The CFLAGS definitions are in the main makefile...

obj-y			= io.o console.o setup.o network.o

