#!/bin/sh
mount -a
mkdir -p /var/run
cat /etc_ro/motd
nvram_daemon&
insmod usbcore.ko
insmod ehci-hcd.ko
insmod ohci-hcd.ko
insmod usb-storage.ko
goahead&

sleep 1
mount -t usbfs none /proc/bus/usb
#for telnet debugging
telnetd

#for syslogd
mkdir -p /var/log
